repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 24.5.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        additional_dependencies:
        -   pytest<8.0.0,>=7.4.3
-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        args: ["--profile", "black"]
-   repo: https://github.com/python/mypy
    rev: v1.10.0
    hooks:
    -   id: mypy
        additional_dependencies:
        -   types-passlib<2.0.0.0,>=1.7.7.20240106
        -   pytest<8.0.0,>=7.4.3
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.0 # Use a recent version
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format
